#ifndef FRONTENDAPPLICATION_HPP
#define FRONTENDAPPLICATION_HPP

#include <gui_generated/common/FrontendApplicationBase.hpp>
#include <touchgfx/Callback.hpp>

class FrontendHeap;

using namespace touchgfx;

class FrontendApplication : public FrontendApplicationBase
{
public:
    FrontendApplication(Model& m, FrontendHeap& heap);
    virtual ~FrontendApplication() { }

    virtual void handleTickEvent()
    {
        model.tick();
        FrontendApplicationBase::handleTickEvent();
    }

    /* Navigation methods not generated by Designer
     * (defects_pmp and input_type are code-only screens). */
    void gotodefects_pmpScreenNoTransition();
    void gotoinput_typeScreenNoTransition();

private:
    touchgfx::Callback<FrontendApplication> m_defects_pmpCallback;
    touchgfx::Callback<FrontendApplication> m_input_typeCallback;

    void gotodefects_pmpScreenNoTransitionImpl();
    void gotoinput_typeScreenNoTransitionImpl();
};

#endif // FRONTENDAPPLICATION_HPP
