"""inspection_logs_with_outcome

Revision ID: 0004
Revises: 0003
Create Date: 2026-05-19 13:24:55.539055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('defect_type_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=8), server_default='DEFECT', nullable=False),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('logged_at', sa.String(), nullable=False),
    sa.Column('received_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))"), nullable=False),
    sa.CheckConstraint("(outcome = 'OK') OR (defect_type_id IS NOT NULL)", name='ck_inspection_logs_defect_type_required_for_defect'),
    sa.ForeignKeyConstraint(['defect_type_id'], ['defect_types.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_logs', schema=None) as batch_op:
        batch_op.create_index('idx_inspection_logs_defect_type', ['defect_type_id'], unique=False)
        batch_op.create_index('idx_inspection_logs_device', ['device_id'], unique=False)
        batch_op.create_index('idx_inspection_logs_logged_at', ['logged_at'], unique=False)
        batch_op.create_index('idx_inspection_logs_operator', ['operator_id'], unique=False)
        batch_op.create_index('idx_inspection_logs_outcome', ['outcome'], unique=False)
        batch_op.create_index('idx_inspection_logs_product', ['product_id'], unique=False)
        batch_op.create_index('idx_inspection_logs_received_at', ['received_at'], unique=False)

    # Migrate existing defect_logs rows → inspection_logs (all become outcome=DEFECT)
    op.execute(
        """
        INSERT INTO inspection_logs
            (id, device_id, operator_id, defect_type_id, product_id,
             outcome, note, logged_at, received_at)
        SELECT id, device_id, operator_id, defect_type_id, product_id,
               'DEFECT', note, logged_at, received_at
        FROM defect_logs
        """
    )

    with op.batch_alter_table('defect_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_defect_logs_defect_type'))
        batch_op.drop_index(batch_op.f('idx_defect_logs_device'))
        batch_op.drop_index(batch_op.f('idx_defect_logs_logged_at'))
        batch_op.drop_index(batch_op.f('idx_defect_logs_operator'))
        batch_op.drop_index(batch_op.f('idx_defect_logs_product'))
        batch_op.drop_index(batch_op.f('idx_defect_logs_received_at'))

    op.drop_table('defect_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('operator_id', sa.INTEGER(), nullable=False),
    sa.Column('defect_type_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=140), nullable=True),
    sa.Column('logged_at', sa.VARCHAR(), nullable=False),
    sa.Column('received_at', sa.VARCHAR(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))"), nullable=False),
    sa.ForeignKeyConstraint(['defect_type_id'], ['defect_types.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defect_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_defect_logs_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_defect_logs_product'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_defect_logs_operator'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_defect_logs_logged_at'), ['logged_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_defect_logs_device'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_defect_logs_defect_type'), ['defect_type_id'], unique=False)

    with op.batch_alter_table('inspection_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_inspection_logs_received_at')
        batch_op.drop_index('idx_inspection_logs_product')
        batch_op.drop_index('idx_inspection_logs_outcome')
        batch_op.drop_index('idx_inspection_logs_operator')
        batch_op.drop_index('idx_inspection_logs_logged_at')
        batch_op.drop_index('idx_inspection_logs_device')
        batch_op.drop_index('idx_inspection_logs_defect_type')

    op.drop_table('inspection_logs')
    # ### end Alembic commands ###
