CATEGORY_KIND_PMP = "PMP"
CATEGORY_KIND_INJECTION = "INJECTION"
CATEGORY_KIND_VALUES = (CATEGORY_KIND_PMP, CATEGORY_KIND_INJECTION)

CATEGORY_DISPLAY_NAMES: dict[str, str] = {
    CATEGORY_KIND_PMP: "PMP Défauts",
    CATEGORY_KIND_INJECTION: "Injection Défauts",
}

OTHER_FALLBACK_LABEL = "Autre — préciser"
DEFECT_TYPES_PER_CATEGORY_CAP = 12
